name: 'Get Package'
description: 'Install packages from OS package manager'
author: Justin Le
inputs:
  apt-get:
    description: |
      Space-separated list of packages to install using apt-get.  Will
      only run if on ubuntu.
    required: false
  brew:
    description: |
      Space-separated list of packages to install using brew install.  Will
      only run if on OSX.
    required: false
branding:
  icon: arrow-down
  color: white
runs:
  using: 'node12'
  main: 'index.js'

